services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./home_assistant_config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
      - /var/run/docker.sock:/var/run/docker.sock:rw
    restart: unless-stopped
    privileged: true
    network_mode: host
  wakeword:
    image: "rhasspy/wyoming-openwakeword"
    ports:
      - 10400:10400
    command:
      - "--preload-model"
      - "ok_nabu"
  microphone:
    container_name: "microphone"
    build: https://github.com/rhasspy/wyoming-mic-external.git
    ports:
      - "10600:10600"
    devices:
      - /dev/snd:/dev/snd
    group_add:
      - audio
    command:
      - "--device"
      - "sysdefault"
      - "--debug"
  playback:
    container_name: "playback"
    build: https://github.com/rhasspy/wyoming-snd-external.git
    ports:
      - "10601:10601"
    devices:
      - /dev/snd:/dev/snd
    group_add:
      - audio
    command:
      - "--device"
      - "sysdefault"
      - "--debug"
  satellite:
    container_name: "satellite"
    build: https://github.com/rhasspy/wyoming-satellite.git
    ports:
      - "10700:10700"
    command:
      - "--name"
      - "my satellite"
      - "--mic-uri"
      - "tcp://microphone:10600"
      - "--snd-uri"
      - "tcp://playback:10601"
      - "--debug"
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    ports:
      - 11434:11434
    volumes:
      - ${HOME}.ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  ollama-pull-llama:   
    image: ollama/ollama:latest
    container_name: ollama-pull-llama
    volumes:
      - ${HOME}/.ollama:/root/.ollama
    entrypoint: /bin/sh
    command:
      - "-c"
      - "sleep 3; OLLAMA_HOST=ollama:11434 ollama pull llama3.2; OLLAMA_HOST=ollama:11434 ollama pull nomic-embed-text"
    depends_on:
      - ollama
  postgres:
    image: postgres
    container_name: postgres
    volumes:
      - "postgres-data:/var/lib/postgres/:delegated"
    ports:
      - "5432:5432"
# TODO: bind mount this?
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
volumes:
  postgres-data:
    driver: local
