services:
  speech_to_text:
    image: "rhasspy/wyoming-whisper"
    group_add:
      - video # for gpu decoding
    ports:
      - 10300:10300
    volumes:
      - ./speech_to_text:/data
    devices:
      - /dev/dri:/dev/dri
      - /dev/kfd:/dev/kfd
    command: [ "--model", "medium-int8", "--language", "en" ]      
  text_to_speech:
    image: "rhasspy/wyoming-piper"
    ports:
      - 10200:10200
    volumes:
      - ./text_to_speech:/data
    command: ["--voice", "en_US-lessac-medium" ]      
  playback:
    image: "playback:latest"
    container_name: "playback"
    environment:
      DISABLE_RTKIT: y
      XDG_RUNTIME_DIR: /tmp
      PIPEWIRE_RUNTIME_DIR: /tmp
      PULSE_RUNTIME_DIR: /tmp
    ports:
      - "10601:10601"
    devices:
      - /dev/snd:/dev/snd
    volumes:
      - /var/run/user/1000/pipewire-0:/tmp/pipewire-0
    group_add:
      - audio
    command:
      - "--device"
      - "default:CARD=USB"
      - "--program"
      - "pw-cat -p -"
      - "--uri"
      - "tcp://0.0.0.0:10601"
    restart: unless-stopped
#   satellite:
#     image: "satellite:latest"
# #    container_name: "satellite"
# #    build: https://github.com/rhasspy/wyoming-satellite.git
#     devices:
#       - /dev/snd:/dev/snd
#     volumes:
#       - /var/run/user/1000/pipewire-0:/tmp/pipewire-0
#     environment:
#       DISABLE_RTKIT: y
#       XDG_RUNTIME_DIR: /tmp
#       PIPEWIRE_RUNTIME_DIR: /tmp
#       PULSE_RUNTIME_DIR: /tmp
#     ports:
#       - "10700:10700"
#     command:
#       - "--name"
#       - "satellite"
#      - "--snd-uri"
#      - "tcp://playback:10601"
#       - "--mic-command"
#       - "pw-record -"
#       # - "--snd-command"
#       # - "pw-cat -p -"
#     restart: unless-stopped
#     depends_on:
#       - speech_to_text
#       - text_to_speech
#       - ollama
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    ports:
      - 11434:11434
    volumes:
      - ${HOME}.ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  ollama-pull-llama:   
    image: ollama/ollama:latest
    container_name: ollama-pull-llama
    volumes:
      - ${HOME}/.ollama:/root/.ollama
    entrypoint: /bin/sh
    command:
      - "-c"
      - "sleep 3; OLLAMA_HOST=ollama:11434 ollama pull llama3.2; "
    depends_on:
      - ollama
